version: '3.9'

services:
  web:
    image: devops22003/speedy-bites:latest
    container_name: speedy_bites_web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=super-secret-key
      - MONGO_USERNAME=salilgupta332
      - MONGO_PASSWORD=Speedy123
      - MONGO_CLUSTER=cluster0.icd6aqk.mongodb.net
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000